-- CreateTable
CREATE TABLE "Ajo" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "reitti" TEXT NOT NULL,
    "km" INTEGER NOT NULL,
    "ajaja" TEXT NOT NULL,
    "pvm" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
